# Cloudflare Pages 配置
# 注意：Pages 项目主要通过 Web 界面配置，此文件仅用于本地开发

name = "shuqian"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# Pages Functions 配置
[build]
command = ""
cwd = ""

# 环境变量（通过 Pages 控制台配置）
[env.production.vars]
# 在 Cloudflare Pages 控制台中配置环境变量

# D1 数据库绑定（通过 Pages 控制台配置）
# 在 Pages 项目设置 -> Functions -> Bindings 中添加：
# 变量名: DB
# 类型: D1 Database
