name = "bookmark-manager"
compatibility_date = "2024-01-01"

[env.production]
name = "bookmark-manager"

[[env.production.d1_databases]]
binding = "DB"
database_name = "bookmark-manager-db"
database_id = "your-database-id-here"

[env.development]
name = "bookmark-manager-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "bookmark-manager-dev"
database_id = "your-dev-database-id-here"
