name = "shuqian"
compatibility_date = "2024-01-01"

[env.production]
# D1数据库绑定
[[env.production.d1_databases]]
binding = "DB"
database_name = "shuqian"
database_id = "311470f8-d59d-4e1c-9b4e-fe07c5472d51"

[env.development]
# 本地开发环境配置
[[env.development.d1_databases]]
binding = "DB"
database_name = "bookmark-manager"
database_id = "your-local-database-id-here"
